characters = [
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Goofy",
    "Pluto",
    "Simba",
    "Nala",
    "Mufasa",
    "Scar",
    "Timón",
    "Pumba",
    "Ariel",
    "Sebastián",
    "Flounder",
    "Bella",
    "Bestia",
    "Aladdín",
    "Jasmín",
    "Genio",
    "Abu",
    "Woody",
    "Buzz Lightyear",
    "Jessie",
    "Mr. Potato Head",
    "Remy",
    "Linguini",
    "WALL·E",
    "EVE",
    "Elsa",
    "Anna",
    "Olaf",
    "Kristoff",
    "Rayo McQueen",
    "Mate",
    "Nemo",
    "Dory",
    "Marlin",
    "Shrek",
    "Burro",
    "Fiona",
    "Gato con Botas",
    "Po",
    "Tigresa",
    "Kung Fu Panda Maestro Shifu",
    "Megamind",
    "Hiccup",
    "Chimuelo",
    "Gru",
    "Minion Bob",
    "Minion Kevin",
    "Minion Stuart"
]

description = "Dibujo animado"