characters = [
    "Marcelo Tinelli",
    "Susana Giménez",
    "Mirtha Legrand",
    "Jorge Rial",
    "Santiago del Moro",
    "Guido Kaczka",
    "Andy Kusnetzoff",
    "Mariana Fabbiani",
    "Marcelo Polino",
    "Ángel de Brito",
    "Pampita Ardohain",
    "Florencia Peña",
    "Adrián Suar",
    "Nicolás Vázquez",
    "Natalia Oreiro",
    "Ricardo Darín",
    "Luis Brandoni",
    "Griselda Siciliani",
    "Carla Peterson",
    "Facundo Arana",
    "Luciano Castro",
    "Nancy Dupláa",
    "Pablo Echarri",
    "Diego Ramos",
    "Florencia de la V",
    "Lizy Tagliani",
    "Marley (Alejandro Wiebe)",
    "Lali Espósito",
    "Tini Stoessel",
    "Cris Morena",
    "Nicolás Cabré",
    "Eugenia 'La China' Suárez",
    "Benjamín Vicuña",
    "Juana Viale",
    "Dady Brieva",
    "Miguel del Sel",
    "Pablo Granados",
    "Pachu Peña",
    "José María Listorti",
    "Denise Dumas",
    "Paula Chaves",
    "Pedro Alfonso",
    "Zaira Nara",
    "Wanda Nara",
    "Nicole Neumann",
    "Moria Casán",
    "Carmen Barbieri",
    "Georgina Barbarossa",
    "Verónica Lozano",
    "Germán Paoloski",
    "Iván de Pineda",
    "Julián Weich",
    "Diego Leuco",
    "Cristina Pérez",
    "Rodolfo Barili",
    "Sergio Lapegüe",
    "Eduardo Feinmann",
    "Jonatan Viale",
    "Jorge Lanata",
    "Luis Majul",
    "Baby Etchecopar",
    "Antonio Laje",
    "Débora Plager",
    "Viviana Canosa",
    "Esteban Trebucq",
    "Marina Calabró",
    "Silvio Soldán",
    "Leo Montero",
    "Ronnie Arias",
    "Catherine Fulop",
    "Marcelo Longobardi",
    "Alejandro Fantino",
    "Mariano Iúdica",
    "Beto Casella",
    "Horacio Cabak",
    "Diego Korol",
    "Fabián Doman",
    "Fernando Dente",
    "Jey Mammon",
    "Roberto Pettinato",
    "Clemente Cancela",
    "Migue Granados",
    "Grego Rossello",
    "Nico Occhiato",
    "Flor Jazmín Peña",
    "Sofía Morandi",
    "Belu Lucius",
    "Diego Leuco",
    "Lucas Spadafora",
    "Damián Betular",
    "Donato de Santis",
    "Germán Martitegui",
    "Carina Zampini",
    "Andrea Politti",
    "Jesica Cirio",
    "Santiago del Moro",
    "Wanda Nara"
]